title: 2manylogs

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

nav_expand: true

plugins:
  - jekyll-include-cache


  tag_colors:
  tech: [esp32, arduino, jekyll, iot, python]
  activity: [setup, debug, experiment, build, refactor, research]
  context: [learning, idea, note]
